### ISSUE TITLE
403: Forbidden

### ISSUE THREAD

**Issue by tgrahn2** [SalesforceCommerceCloud/sfcc-sample-apps#243]
I can't seem to get past this error - I believe everything is setup correctly but doesn't appear to be connecting.  Just downloaded the most recent version this morning (1.0.0-alpha.5) and still no change.   Any help would greatly be appreciated.

One thing I've noticed was a double / in the URL - not sure if that is causing issues or not:
```
https://0dnz6oep.api.commercecloud.salesforce.com/search/shopper-search/v1//organizations/f_ecom_zzsa_060/product-search?q=suits&siteId=RefArch
```

Pertinent settings in my api.js file - the first two were setup for me in Account Manager: 
- COMMERCE_CLIENT_CLIENT_ID
- COMMERCE_SESSION_SECRET
- COMMERCE_CLIENT_SHORT_CODE

Full error: 
```
storefront-lwc: Error in requestWithTokenRefresh() ResponseError: 403 Forbidden
storefront-lwc:     at /Users/tgrahn/Documents/dev/sfcc-sample-apps/node_modules/@commerce-apps/core/dist/base/staticClient.js:58:19
storefront-lwc:     at Generator.next (<anonymous>)
storefront-lwc:     at /Users/tgrahn/Documents/dev/sfcc-sample-apps/node_modules/tslib/tslib.js:113:75
storefront-lwc:     at new Promise (<anonymous>)
storefront-lwc:     at Object.__awaiter (/Users/tgrahn/Documents/dev/sfcc-sample-apps/node_modules/tslib/tslib.js:109:16)
storefront-lwc:     at getObjectFromResponse (/Users/tgrahn/Documents/dev/sfcc-sample-apps/node_modules/@commerce-apps/core/dist/base/staticClient.js:51:20)
storefront-lwc:     at /Users/tgrahn/Documents/dev/sfcc-sample-apps/node_modules/@commerce-apps/core/dist/base/staticClient.js:129:49
storefront-lwc:     at Generator.next (<anonymous>)
storefront-lwc:     at fulfilled (/Users/tgrahn/Documents/dev/sfcc-sample-apps/node_modules/tslib/tslib.js:110:62)
storefront-lwc:     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
storefront-lwc:   response: Response {
storefront-lwc:     size: 0,
storefront-lwc:     timeout: 0,
storefront-lwc:     [Symbol(Body internals)]: { body: [Minipass], disturbed: false, error: null },
storefront-lwc:     [Symbol(Response internals)]: {
storefront-lwc:       url: 'https://0dnz6oep.api.commercecloud.salesforce.com/search/shopper-search/v1//organizations/f_ecom_zzsa_060/product-search?q=suits&siteId=RefArch',
storefront-lwc:       status: 403,
storefront-lwc:       statusText: 'Forbidden',
storefront-lwc:       headers: [Headers],
storefront-lwc:       counter: 0,
storefront-lwc:       trailer: [Promise]
storefront-lwc:     }
storefront-lwc:   }
storefront-lwc: }
```

**Comment by tgrahn2** [comment]
This might have more to do with my ClientID JWT not having enough scopes defined that are needed for the sample app.  Will adjust this and see if it fixes my error.

**Comment by jbegleiter-sf** [comment]
Hey @tgrahn2 ,

This looks like a permissions issue (e.g., scope setup for your client ID). Please post this to the CCDC forums if you are still experiencing issues.

Cheers,
Josh
