### ISSUE TITLE
Running sfcc-sample-apps. Search fails when requesting a token

### ISSUE THREAD

**Issue by tkrugg** [SalesforceCommerceCloud/sfcc-sample-apps#246]
I've successfully followed the setup steps from the readme.

However when running it, I can't seam to be able to perform a search.

​

### How to reproduce:

​

1. Follow the setup steps of the readme, run the app with `yarn start:dev` and open http://localhost:3000

2. In the Summer Look section, click on "Shop now", which should take you to take you to http://localhost:3000/search/Tops (see GIF recording)

3. The search returns no results because the request returned 404.

​

In the terminal, this error shows up:

​
```
storefront-lwc: Authorization Token has expired Response {
storefront-lwc:   size: 0,
storefront-lwc:   timeout: 0,
storefront-lwc:   [Symbol(Body internals)]: {
storefront-lwc:     body: Minipass {
storefront-lwc:       _events: [Object: null prototype],
storefront-lwc:       _eventsCount: 5,
storefront-lwc:       _maxListeners: undefined,
storefront-lwc:       pipes: [Yallist],
storefront-lwc:       buffer: [Yallist],
storefront-lwc:       writable: false,
storefront-lwc:       readable: true,
storefront-lwc:       [Symbol(kCapture)]: false,
storefront-lwc:       [Symbol(flowing)]: false,
storefront-lwc:       [Symbol(paused)]: false,
storefront-lwc:       [Symbol(objectMode)]: false,
storefront-lwc:       [Symbol(encoding)]: null,
storefront-lwc:       [Symbol(decoder)]: null,
storefront-lwc:       [Symbol(EOF)]: true,
storefront-lwc:       [Symbol(emittedEnd)]: false,
storefront-lwc:       [Symbol(emittingEnd)]: false,
storefront-lwc:       [Symbol(closed)]: false,
storefront-lwc:       [Symbol(bufferLength)]: 259,
storefront-lwc:       [Symbol(destroyed)]: false
storefront-lwc:     },
storefront-lwc:     disturbed: false,
storefront-lwc:     error: null
storefront-lwc:   },
storefront-lwc:   [Symbol(Response internals)]: {
storefront-lwc:     url: 'https://kv7kzm78.api.commercecloud.salesforce.com/customer/shopper-customers/v1/organizations/f_ecom_ZZGK_004/customers/actions/login?clientId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxe&siteId=RefArch',
storefront-lwc:     status: 404,
storefront-lwc:     statusText: 'Not Found',
storefront-lwc:     headers: Headers { [Symbol(map)]: [Object: null prototype] },
storefront-lwc:     counter: 0,
storefront-lwc:     trailer: Promise { [Headers] }
storefront-lwc:   }
storefront-lwc: }
storefront-lwc: Error in requestWithTokenRefresh() ResponseError: 404 Not Found
storefront-lwc:     at Object.<anonymous> (/Users/youcefmammar/algolia/sfcc-sample-apps/node_modules/commerce-sdk/dist/helpers.js:36:13)
storefront-lwc:     at Generator.next (<anonymous>)
storefront-lwc:     at fulfilled (/Users/youcefmammar/algolia/sfcc-sample-apps/node_modules/tslib/tslib.js:110:62)
storefront-lwc:     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
storefront-lwc:   response: Response {
storefront-lwc:     size: 0,
storefront-lwc:     timeout: 0,
storefront-lwc:     [Symbol(Body internals)]: { body: [Minipass], disturbed: false, error: null },
storefront-lwc:     [Symbol(Response internals)]: {
storefront-lwc:       url: 'https://kv7kzm78.api.commercecloud.salesforce.com/customer/shopper-customers/v1/organizations/f_ecom_ZZGK_004/customers/actions/login?clientId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxe&siteId=RefArch',
storefront-lwc:       status: 404,
storefront-lwc:       statusText: 'Not Found',
storefront-lwc:       headers: [Headers],
storefront-lwc:       counter: 0,
storefront-lwc:       trailer: [Promise]
storefront-lwc:     }
storefront-lwc:   }
storefront-lwc: }
``` 
​NB: I've replace the API client with `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

​

​

**Comment by jbegleiter-sf** [comment]
Hey @tkrugg ,

A 404 typically indicates that your org/realm is incorrect and therefore not found. Can you please post this to the CCDC forums ( https://developer.commercecloud.com/s/ )? Someone there will be better equipped to answer this question.

Cheers,
Josh
