### ISSUE TITLE
Features related to Search not working in sample app

### ISSUE THREAD

**Issue by diegoavilaACN** [SalesforceCommerceCloud/sfcc-sample-apps#250]
I've installed the sample apps following all of the instructions. Whenever I try to access any search page, I run into the following error:
```
Cannot read property 'map' of null
TypeError: Cannot read property 'map' of null
    at SearchSort.get viewOptions [as viewOptions] (http://localhost:3000/app.js:17146:24)
    at tmpl$h (http://localhost:3000/app.js:17113:26)
    at http://localhost:3000/app.js:9319:23
    at ReactiveObserver.observe (http://localhost:3000/app.js:4805:9)
    at isUpdatingTemplate (http://localhost:3000/app.js:9270:11)
    at runWithBoundaryProtection (http://localhost:3000/app.js:10162:7)
    at evaluateTemplate (http://localhost:3000/app.js:9254:5)
    at invokeComponentRenderMethod (http://localhost:3000/app.js:9446:41)
    at renderComponent (http://localhost:3000/app.js:9549:20)
    at rehydrate (http://localhost:3000/app.js:9805:24)

```

Is there any step I skipped while installing or  missing configuration that might be causing this?

**Comment by diegoavilaACN** [comment]
Solved! The sandbox was missing the Sorting Rules in BM.
